# Site settings
title: Jay Thrash
email: jay@jaythrash.com
description: > # this means to ignore newlines until "baseurl:"
  Insert coffee here
baseurl: 
url: "http://jaythrash.com" # the base hostname & protocol for your site
twitter_username: jaythrash
github_username:  jaythrash


# Build settings
markdown: kramdown
highlighter: pygments
paginate: 10
destination: public

collections:
  talks:
    output: true
